# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20170414_2329'),
        ('dojo_secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Login')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo_secrets_app.Secret')),
            ],
        ),
    ]
