# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets_app', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secret',
            name='likes_posted',
            field=models.ManyToManyField(related_name='liked_secrets', to='dojo_secrets_app.Like'),
        ),
    ]
