# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets_app', '0003_auto_20170420_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='likes_posted',
        ),
        migrations.AddField(
            model_name='like',
            name='secrets',
            field=models.ManyToManyField(to='dojo_secrets_app.Secret'),
        ),
    ]
