# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets_app', '0004_auto_20170421_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secrets',
        ),
        migrations.AddField(
            model_name='like',
            name='secret',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojo_secrets_app.Secret'),
            preserve_default=False,
        ),
    ]
